services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rafa123
      - POSTGRES_DB=entitystudy
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=rafa@mail.com
      - PGADMIN_DEFAULT_PASSWORD=rafa123
    ports:
      - "5050:80"
    restart: always